Vagrant.configure(2) do |config|

  config.vm.box = 'ubuntu/trusty64'

  config.vm.provision :docker do |docker|
    docker.run 'osiam',
               :image => 'osiamorg/osiam:1.3.2',
               :args => '-p 8080:8080 -p 5432:5432'
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.network :forwarded_port,
                    :guest => 5432, :host => 5432

  config.vm.network :forwarded_port,
                    :guest => 8080, :host => 8080

end
