Vagrant.configure(2) do |config|

  config.vm.box = 'puppetlabs/debian-7.8-64-puppet'

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path = 'puppet/modules'
    puppet.options = '--test'
  end

  config.vm.provision :file, :source => 'setup_data.sql', :destination => '/tmp/setup_data.sql'

  config.vm.provision :shell, :path => 'bootstrap.sh'


  config.vm.network :forwarded_port,
                    :guest => 5432, :host => 5432

  config.vm.network :forwarded_port,
                    :guest => 8080, :host => 8080

end
